### ISSUE TITLE
[ANDROID] build error (cordova 8 / android 7)

### ISSUE THREAD

**Issue by moradec** [j3k0/cordova-plugin-purchase#659]
Windows 10
Cordova 8
Android 7.0.0
Plugin Version: 7.1.0

After upgrading from cordova 6.x to cordova 8 the build fails with the following error message:

> error: package com.android.vending.billing does not exist
> error: cannot find symbol
> error: package IInAppBillingService does not exist

It looks like something has changed in the newer android billing framework, the class is missing. Is there a workaround to proceed working with cordova 8/android 7.0.0 or can you please update the plugin(...cause i love it)?

BR,
Andreas

**Comment by souly1** [comment]
+1
any update about this?

**Comment by RenaudROHLINGER** [comment]
Pretty sure the problem is from the major breaking change of the version of Android 7.0.0 as mentioned on their article :
https://cordova.apache.org/announcements/2017/12/04/cordova-android-7.0.0.html

So the problem must be a path issue in something like the plugin.xml file.
I tried to fix this but I don't know enough this plugin to find a solution :/

**Comment by moradec** [comment]
Had another problem with cordova 8 (https://stackoverflow.com/questions/47946118/vsts-cordova-ios-build-on-macincloud-agent-failed-cannot-read-property-fail) so i downgraded to cordova 7.1.0 which seems to work on android and ios.

cordova 7.1.0
android 6.3
ios 4.5.4

**Comment by rafaellop** [comment]
@j3k0 This is critical issue. 

Android@7.0.0 + Cordova 8:

```
:app:compileReleaseJavaWithJavacC:\Users\user\Desktop\Apps\APP\platforms\android\app\src\main\java\com\smartmobilesoftware\util\IabHelper.java:33: error: package com.android.vending.billing does not exist
import com.android.vending.billing.IInAppBillingService;
                                  ^
C:\Users\user\Desktop\Apps\APP\platforms\android\app\src\main\java\com\smartmobilesoftware\util\IabHelper.java:102: error: cannot find symbol
    IInAppBillingService mService;
    ^
  symbol:   class IInAppBillingService
  location: class IabHelper
C:\Users\user\Desktop\Apps\APP\platforms\android\app\src\main\java\com\smartmobilesoftware\util\IabHelper.java:234: error: package IInAppBillingService does not exist
                mService = IInAppBillingService.Stub.asInterface(service);
                                               ^
Note: Some input files use or override a deprecated API.
 FAILED

```

**Comment by Bandito11** [comment]
I have the same problem too.

**Comment by Bandito11** [comment]
What @mlegenhausen wrote in his post appears to be working. At least it built correctly. 

For future readers, If I don't respond in a month time (at most) from this post it meant the fix worked correctly. :)

**Comment by Ralpharoo** [comment]
I am still seeing this on PhoneGapBuild, even after linking to the current development build with this fix;

`<plugin spec="https://github.com/j3k0/cordova-plugin-purchase" source="git">
        <param name="BILLING_KEY" value="..."/>
</plugin>`

Build
>Fetching plugin "https://github.com/j3k0/cordova-plugin-purchase" via git clone
Using shallow clone
Repository "https://github.com/j3k0/cordova-plugin-purchase" checked out to git ref "master" at "12e9fc4".
Installing "cc.fovea.cordova.purchase" at "7.1.0" for android


Error;
> BUILD FAILED in 3s
38 actionable tasks: 38 executed
Error: /gradlew: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
/app/src/main/java/com/smartmobilesoftware/util/IabHelper.java:33: error: package com.android.vending.billing does not exist
import com.android.vending.billing.IInAppBillingService;
                                  ^
/app/src/main/java/com/smartmobilesoftware/util/IabHelper.java:102: error: cannot find symbol
    IInAppBillingService mService;
    ^
  symbol:   class IInAppBillingService
  location: class IabHelper
/app/src/main/java/com/smartmobilesoftware/util/IabHelper.java:234: error: package IInAppBillingService does not exist
                mService = IInAppBillingService.Stub.asInterface(service);


Any immediate suggestions?

Thanks in advanced,

**Comment by aesculus** [comment]
Not working for me with PGB either. :-(

**Comment by distante** [comment]
I have a gist with a hook that I use before build so the folder are automatically copied. It also contains the fix for Admobfree because my project also has Admobfree but you can comment this part if you do not need it.

https://gist.github.com/distante/c7552ac53659fd5efeb12e83141c3034

**Comment by aesculus** [comment]
Per #669  this was fixed in V7.1.2 and verified with PGB CLI 8.0.0

**Comment by hasancansaral** [comment]
I am still getting this issue with:

```
Ubuntu 18.04 OSX Sierra 10.12.04
ionic (Ionic CLI)  : 4.10.3
Ionic Framework    : ionic-angular 3.9.2
cordova (Cordova CLI) : 8.0.0
Cordova Platforms     : android 7.0.0
```
