### ISSUE TITLE
[ANDROID] getProductDetails removed from plugin-bridge.js

### ISSUE THREAD

**Issue by pyroxiano** [j3k0/cordova-plugin-purchase#916]
[ANDROID] getProductDetails removed from plugin-bridge.js

OS: Android 9
Cordova: 9.0.0 (Cordova Android 8.0.0)
Device: Samsung S8+
Plugin Version: 8.1.1

### Expected behavior
store.android.getProductDetails to retrieve product details

### Observed behavior
The following error occurs:
Uncaught TypeError: store.android.getProductDetails is not a function

### Steps to reproduce
Call the following line from the console:

```store.android.getProductDetails( () => {}, () => {}, ["testSku"] );```

### Comment
The app we're developing has over 1000 IAPs, and the app gets data asychronously as the user browses through it, which means we can't simply register all of our SKUs when the app starts.
To work around this, I was calling store.android.getProductDetails directly, which worked fine in the old 7.4.3 version, but now I've updated our app to use 8.1.1, it stopped working due to
the changes in https://github.com/j3k0/cordova-plugin-purchase/commit/ae0e8c61bd22f8bca8af00c7eeaa48b606c55144.

Is there a reason that this method got removed? And is it possible to put it back in again?

I'm using `storekit.load( skus, success, fail );` for iOS, which works fine.

As a workaround I can call `cordova.exec(success, errorCb(fail), "InAppBillingPlugin", "getProductDetails", [skus]);`, which still works.

**Comment by j3k0** [comment]
`store.android.getProductDetails` was an internal method, it wasn't ever meant to be used directly. It got removed because it's not supported by Windows 10 and the new Android implementation (#911).

Out of curiosity, did you try registering all your SKUs? As far as I know, loading a 1000 SKUs is acceptable (it's probably not over 50kB of gzipped data).

**Comment by j3k0** [comment]
No reply, closing issue.

There's no way we're gonna support backward compatibility with internal methods anyway.
