### ISSUE TITLE
Plugin Not Compatible with SDK 34

### ISSUE THREAD

**Issue by Andalusio** [j3k0/cordova-plugin-purchase#1580]
Hi. I've been getting the "IabHelper.java:32: error: package com.android.vending.billing does not exist" error message on Command Prompt while attempting to increase my SDK number to 34, as demanded by Google Play Console. The old solution to copy-paste IInAppBillingService.aidl to \platforms\android\app\src\main\aidl\com\android\vending\billing doesn't work in this scenario. Someone might need to update this plugin ASAP.

**Comment by michellavezzo** [comment]
Up

**Comment by danieldanielecki** [comment]
up, too

**Comment by hugomc92** [comment]
Up

**Comment by Xdabier** [comment]
Up

**Comment by hooliapps** [comment]
Hello. I used the plugin with SDK 34 and Android Studio Jellyfish with no error.

**Comment by EYALIN** [comment]
@Andalusio can you please give a little bit more info ?
I'm using SDK 34 as well, and all ok 

maybe you don't have latest version ?
also, did you upgrade the cordoava version ?

**Comment by Andalusio** [comment]
I might need to look into it again then. The last time I tried, my build failed when I upgraded the target SDK to 34, but also Cordova Android to the latest version.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by EYALIN** [comment]
@Andalusio feel free to share any errors you have, because I did the upgrade already and handled them
also, I have upgraded all cordova community plugins to support SDK 34:
https://github.com/EYALIN?tab=repositories&q=community&type=&language=&sort=

in the link above you can see all the plugins I maintain for the community. (15± plugins)

**Comment by j3k0** [comment]
Are you using the latest version of the plugin? (v13)

**Comment by j3k0** [comment]
Old plugin version v11 is using APIs that Google has removed, upgrade is necessary (app updates on Google Play won't be accepted with the old version anyway).

**Comment by danieldanielecki** [comment]
I'm on `13.6.0` (https://github.com/Doyban/GalacticShooter/blob/feature/android/cordova/package.json) and still seeing the warning.

![Screenshot 2024-08-24 at 19 28 48](https://github.com/user-attachments/assets/6d49b478-4145-4491-961c-2559f8d429c2)

**Comment by danieldanielecki** [comment]
https://github.com/j3k0/cordova-plugin-purchase/releases/tag/v13.11.0 looks like fixed it
