### ISSUE TITLE
Get rid of hook script after we release cordova-android update

### ISSUE THREAD

**Issue by brodybits** [j3k0/cordova-plugin-purchase#760]
As I said in #759 you should not need a hook script once we release the next cordova-android update. I already tested that it is possible to install, build, and uninstall `https://github.com/j3k0/cordova-plugin-purchase#v7.1.0` (version before you added extra aidl entry and hook script) with the proposed cordova-android update.

Plugin hook scripts can be sensitive to plugin structure and do not work with PhoneGap Build.

**Comment by aesculus** [comment]
I wonder if this is why I cannot compile on PGB with CLI 8.1.1 (Android 7.1.2)?  

I get the error:
`Fetching plugin "cc.fovea.cordova.purchase@7.2.0" via npm Installing "cc.fovea.cordova.purchase" at "7.2.0" for android Android Studio project detected Error during processing of action! `

and

`Failed to install 'cc.fovea.cordova.purchase': TypeError: Uh oh! Path must be a string. Received undefined at assertPath (path.js:7:11) `

**Comment by aesculus** [comment]
UPDATE: I tried it with 7.2.8 and got by the above error but then ran into this (using NPM as source):
`:app:compileReleaseJavaWithJavac/app/src/main/java/com/smartmobilesoftware/util/IabHelper.java:33: error: package com.android.vending.billing does not exist
import com.android.vending.billing.IInAppBillingService;
                                  ^
/app/src/main/java/com/smartmobilesoftware/util/IabHelper.java:102: error: cannot find symbol
    IInAppBillingService mService;
    ^
  symbol:   class IInAppBillingService
  location: class IabHelper
/app/src/main/java/com/smartmobilesoftware/util/IabHelper.java:234: error: package IInAppBillingService does not exist
                mService = IInAppBillingService.Stub.asInterface(service);
                                               ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /app/src/main/java/nl/xservices/plugins/SocialSharing.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
3 errors`

**Comment by brodybits** [comment]
Looks like this has been done, thanks @j3k0!

**Comment by j3k0** [comment]
Thanks to you Chris! :)

**Comment by aesculus** [comment]
Can you please state the version of the plugin that this has been fixed on?  

Also does it address #803 or not. That thread sort of sounded like it could not be fixed until/if PGB updated to a more recent build.

**Comment by j3k0** [comment]
I added some instructions about this in the README.
https://github.com/j3k0/cordova-plugin-purchase/blob/master/README.md#install-the-plugin-phonegap

**Comment by aesculus** [comment]
:-)
