### ISSUE TITLE
Can't compile in Xcode 6.4 - error: no visible @interface for 'NSData' 

### ISSUE THREAD

**Issue by beccax** [j3k0/cordova-plugin-purchase#251]
See below for the two errors.   I had an April 2015 version of the plugin that  worked great on earlier version of Mac OS and Xcode, and even after upgraded to Yosemite and Xcode 6.4 it was compiling fine.  But I had to upgrade to the latest plugin due to other issues, and that's when I started seeing the errors below.  

I tried removing and re-installing the plugins, removing and re-installing iOS platforms, but the error persists. Much appreciate any pointers you can give.  

/Users/<user>/tg_app/platforms/ios/<app name>/Plugins/cc.fovea.cordova.purchase/InAppPurchase.m:421:60: error: no visible @interface for 'NSData' declares the
      selector 'cdv_base64EncodedString'
                                transactionReceipt = [[transaction transactionReceipt] cdv_base64EncodedString];
                                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~
/Users/<user>/tg_app/platforms/ios/<app name>/Plugins/cc.fovea.cordova.purchase/InAppPurchase.m:446:60: error: no visible @interface for 'NSData' declares the
      selector 'cdv_base64EncodedString'
                                transactionReceipt = [[transaction transactionReceipt] cdv_base64EncodedString];
                                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~

I read online this is due to NSData+Base64.h not being imported.  But I can see the line 
     #import <Cordova/NSData+Base64.h> 
in InAppPurchase.h which is included in InAppPurchase.m.  So unless some how Cordova's version of that file is not able to be referenced?  How could I check that?  For reference, I have Cordova 4.2.0.  

Thanks!

**Comment by JotaP** [comment]
I solved this issue yesterday updating my Cordova version to 5.1.1. Good luck!

PS: I do not compile from xCode but with cordova build.

**Comment by beccax** [comment]
Thanks! Will try that.

R

**Comment by Inferner** [comment]
I am having the same problem. Is update the only way? I am scared to update. Will it break other stuff?

**Comment by JotaP** [comment]
I think it will be easier to update Cordova than to look for a workaround for this problem, but that's just my opinion (In my case, the project was still very little so I didn't have any side effects when I updated Cordova to make this plugin work).

Good luck anyway!

**Comment by Inferner** [comment]
:) Updated and it worked.Everything else looks ok.But gotta test the whole way.

**Comment by JotaP** [comment]
congrats!

**Comment by beccax** [comment]
that worked for me as well, thanks JotaP!

**Comment by beccax** [comment]
thanks, just closed my first issue.
