### ISSUE TITLE
[IOS] Bad product ID is presented in the validation request

### ISSUE THREAD

**Issue by viktorzavadil** [j3k0/cordova-plugin-purchase#1149]
Hi everyone.

I have a few questions about validating process. If my validator is called first time, product ID is presented in the request. If the plugin calls validator repeatdly, ID is filled by bad identifier (looks like bundle ID of application). And `transaction` field has no field `id` and `original_transaction_id` (only `type` and `appStoreReceipt`). And if `transaction` contains `id`, in the root of request body is array `transactions` which contains transaction ID as well.

Please, could somebody explain this behaviour to me? I didn't find anything in plugin documentation about this behaviour.

- Bundle ID of application
  <img width="368" alt="Screen Shot 2021-01-13 at 16 43 14" src="https://user-images.githubusercontent.com/19145428/104476117-2b17e480-55c0-11eb-8e41-1752b87702a8.png">
- Registered products
  <img width="870" alt="Screen Shot 2021-01-13 at 16 36 05" src="https://user-images.githubusercontent.com/19145428/104476197-42ef6880-55c0-11eb-901c-2f03a300d9f5.png">
- First time validation request following purchase
  <img width="477" alt="Screen Shot 2021-01-13 at 17 00 02" src="https://user-images.githubusercontent.com/19145428/104477698-b6de4080-55c1-11eb-947b-0709fd5c8e26.png">
- Repeating validation of receipt
  <img width="431" alt="Screen Shot 2021-01-13 at 16 37 04" src="https://user-images.githubusercontent.com/19145428/104476271-58fd2900-55c0-11eb-84b5-7c2ec5c92751.png">

Thank you for your time.

### System info

```
OSX Catalina 10.15.7
Cordova 9.0.0
cordova-ios 6.1.0
Device: iPhone 6 12.4.9
Plugin Version: 10.5.0
```

### Expected behavior

I expected one of the registrated product ID in the receipt request.

### Observed behavior

In some cases ID is filled by bad identifier. It seems like bundle ID.

I have discovered bad ID is presented if receipt is validated more than first time. The first time call present valid product ID.

**Comment by philmerrell** [comment]
I started seeing this behavior as well. You can certainly filter out products where type is application. Something like:

```
    this.store.ready(() => {
      const products = this.store.products;
      this.products = products.filter(product => product.type !== 'application');
    });
```
But not ideal.

**Comment by OrthoCube** [comment]
I have noticed this in my project, too.

**Comment by j3k0** [comment]
The `application` receipt is sent to refresh the status of all purchases, not a particular purchase. It'll also ensures the app has been downloaded from the AppStore (not side-loaded with potential modifications). You'll notice the field `type` = `"application"`.

If you don't want to refresh application receipts, just do not call `verify()` for `application` products.
